server:
  port: 8080

spring:
  application:
    name: e-evaluation

cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK

eureka:
  client:
    enabled: false

ocds.prefix: ocds-t1s2t3

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full